### PR TITLE
Enhanced Mushrooms compat

### PR DESCRIPTION
**Pull request by Epic312**
Adds integration with Enhanced Mushrooms' mushroom stems. Due to Environmental's mushrooms in swamps feature adding features in a DeferredWorkQueue it depends on the random loading order whether they're replaced by EM mushrooms or not. This fixes that by using ObjectHolders to just stick the stems in there on Environmental's end if EM is installed. I've tested it with the latest GitHub build of EM and it seems to be working.

I think this _should_ work with the latest CF build of EM but if not, it should definitely work with the latest GitHub build, which will be uploaded to CurseForge soon™

### CODE REVIEW

**Comment by Epic312** [comment]
Apparently the Mushroom Marsh was missing EM stems as well for whatever reason. Just pushed a commit to fix that, basically the same code as the swamp fix.

**Comment by bageldotjpg** [comment]
this... ain't it

**Comment by ShockMicro** [comment]
Are you deliberately denying mod compat because you think we're annoying? I understand how you think we're annoying but denying mod compat? That... ain't it.

**Comment by bageldotjpg** [comment]
No, I'm denying it because a mess was made of my code and this can be done in a couple lines in a mods.toml file.

**Comment by ShockMicro** [comment]
ah ok

**Comment by ShockMicro** [comment]
srry

**Comment by bageldotjpg** [comment]
All good.

**Comment by bageldotjpg** [comment]
I do admit, I should have been more clear, but I expected a bit more from Epic than using ObjectHolders and defining feature configs when adding the feature making the method really cluttery. The mods.toml has support for making sure your mod loads before another though, so this all can be fixed there.

**Comment by Epic312** [comment]
Problem is it doesn't. The loading order in mods.toml doesn't affect the setup functions in the core mod classes and DeferredWorkQueues don't help with that either.
I originally tried using mods.toml loading order back in 1.15 but it not working is why I had to add stuff on SwEx's end. I'll try and see if I can use mixins or something to replace the stems in the DefaultBiomeFeatures huge mushroom configs, but if that doesn't work I don't know how I'd make stuff work without doing something on Env's end. And I think ObjectHolders are probably a bit more elegant than my old solution in 1.15, which was to disable adding swamp shrooms on SwEx's end if EM was installed, and then add them on EM's end instead.
I'll keep you updated w/ how the mixin thing works.

**Pull request closed without merging**
